repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.4
    hooks:
      - id: ruff
      - id: ruff-format
  - repo: https://github.com/scanoss/pre-commit-hooks
    rev: v0.2.0
    hooks:
      - id: scanoss-check-undeclared-code

