# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scanoss/api/dependencies/v2/scanoss-dependencies.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from scanoss.api.common.v2 import scanoss_common_pb2 as scanoss_dot_api_dot_common_dot_v2_dot_scanoss__common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='scanoss/api/dependencies/v2/scanoss-dependencies.proto',
  package='scanoss.api.dependencies.v2',
  syntax='proto3',
  serialized_options=b'Z9github.com/scanoss/papi/api/dependenciesv2;dependenciesv2',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n6scanoss/api/dependencies/v2/scanoss-dependencies.proto\x12\x1bscanoss.api.dependencies.v2\x1a*scanoss/api/common/v2/scanoss-common.proto\"8\n\x11\x44\x65pendencyRequest\x12\x14\n\x0c\x64\x65pendencies\x18\x01 \x01(\t\x12\r\n\x05\x64\x65pth\x18\x02 \x01(\x05\"Y\n\x12\x44\x65pendencyResponse\x12\x14\n\x0c\x64\x65pendencies\x18\x01 \x01(\t\x12-\n\x06status\x18\x02 \x01(\x0b\x32\x1d.scanoss.api.common.v2.Status2\xd3\x01\n\x0c\x44\x65pendencies\x12O\n\x04\x45\x63ho\x12\".scanoss.api.common.v2.EchoRequest\x1a#.scanoss.api.common.v2.EchoResponse\x12r\n\x0fGetDependencies\x12..scanoss.api.dependencies.v2.DependencyRequest\x1a/.scanoss.api.dependencies.v2.DependencyResponseB;Z9github.com/scanoss/papi/api/dependenciesv2;dependenciesv2b\x06proto3'
  ,
  dependencies=[scanoss_dot_api_dot_common_dot_v2_dot_scanoss__common__pb2.DESCRIPTOR,])




_DEPENDENCYREQUEST = _descriptor.Descriptor(
  name='DependencyRequest',
  full_name='scanoss.api.dependencies.v2.DependencyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='dependencies', full_name='scanoss.api.dependencies.v2.DependencyRequest.dependencies', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='depth', full_name='scanoss.api.dependencies.v2.DependencyRequest.depth', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=131,
  serialized_end=187,
)


_DEPENDENCYRESPONSE = _descriptor.Descriptor(
  name='DependencyResponse',
  full_name='scanoss.api.dependencies.v2.DependencyResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='dependencies', full_name='scanoss.api.dependencies.v2.DependencyResponse.dependencies', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='scanoss.api.dependencies.v2.DependencyResponse.status', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=189,
  serialized_end=278,
)

_DEPENDENCYRESPONSE.fields_by_name['status'].message_type = scanoss_dot_api_dot_common_dot_v2_dot_scanoss__common__pb2._STATUS
DESCRIPTOR.message_types_by_name['DependencyRequest'] = _DEPENDENCYREQUEST
DESCRIPTOR.message_types_by_name['DependencyResponse'] = _DEPENDENCYRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DependencyRequest = _reflection.GeneratedProtocolMessageType('DependencyRequest', (_message.Message,), {
  'DESCRIPTOR' : _DEPENDENCYREQUEST,
  '__module__' : 'scanoss.api.dependencies.v2.scanoss_dependencies_pb2'
  # @@protoc_insertion_point(class_scope:scanoss.api.dependencies.v2.DependencyRequest)
  })
_sym_db.RegisterMessage(DependencyRequest)

DependencyResponse = _reflection.GeneratedProtocolMessageType('DependencyResponse', (_message.Message,), {
  'DESCRIPTOR' : _DEPENDENCYRESPONSE,
  '__module__' : 'scanoss.api.dependencies.v2.scanoss_dependencies_pb2'
  # @@protoc_insertion_point(class_scope:scanoss.api.dependencies.v2.DependencyResponse)
  })
_sym_db.RegisterMessage(DependencyResponse)


DESCRIPTOR._options = None

_DEPENDENCIES = _descriptor.ServiceDescriptor(
  name='Dependencies',
  full_name='scanoss.api.dependencies.v2.Dependencies',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=281,
  serialized_end=492,
  methods=[
  _descriptor.MethodDescriptor(
    name='Echo',
    full_name='scanoss.api.dependencies.v2.Dependencies.Echo',
    index=0,
    containing_service=None,
    input_type=scanoss_dot_api_dot_common_dot_v2_dot_scanoss__common__pb2._ECHOREQUEST,
    output_type=scanoss_dot_api_dot_common_dot_v2_dot_scanoss__common__pb2._ECHORESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetDependencies',
    full_name='scanoss.api.dependencies.v2.Dependencies.GetDependencies',
    index=1,
    containing_service=None,
    input_type=_DEPENDENCYREQUEST,
    output_type=_DEPENDENCYRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DEPENDENCIES)

DESCRIPTOR.services_by_name['Dependencies'] = _DEPENDENCIES

# @@protoc_insertion_point(module_scope)
