# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scanoss/api/scanning/v2/scanoss-scanning.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from scanoss.api.common.v2 import scanoss_common_pb2 as scanoss_dot_api_dot_common_dot_v2_dot_scanoss__common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='scanoss/api/scanning/v2/scanoss-scanning.proto',
  package='scanoss.api.scanning.v2',
  syntax='proto3',
  serialized_options=b'Z1github.com/scanoss/papi/api/scanningv2;scanningv2',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n.scanoss/api/scanning/v2/scanoss-scanning.proto\x12\x17scanoss.api.scanning.v2\x1a*scanoss/api/common/v2/scanoss-common.proto2[\n\x08Scanning\x12O\n\x04\x45\x63ho\x12\".scanoss.api.common.v2.EchoRequest\x1a#.scanoss.api.common.v2.EchoResponseB3Z1github.com/scanoss/papi/api/scanningv2;scanningv2b\x06proto3'
  ,
  dependencies=[scanoss_dot_api_dot_common_dot_v2_dot_scanoss__common__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None

_SCANNING = _descriptor.ServiceDescriptor(
  name='Scanning',
  full_name='scanoss.api.scanning.v2.Scanning',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=119,
  serialized_end=210,
  methods=[
  _descriptor.MethodDescriptor(
    name='Echo',
    full_name='scanoss.api.scanning.v2.Scanning.Echo',
    index=0,
    containing_service=None,
    input_type=scanoss_dot_api_dot_common_dot_v2_dot_scanoss__common__pb2._ECHOREQUEST,
    output_type=scanoss_dot_api_dot_common_dot_v2_dot_scanoss__common__pb2._ECHORESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SCANNING)

DESCRIPTOR.services_by_name['Scanning'] = _SCANNING

# @@protoc_insertion_point(module_scope)
