# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: scanoss/api/common/v2/scanoss-common.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'scanoss/api/common/v2/scanoss-common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protoc_gen_openapiv2.options import annotations_pb2 as protoc__gen__openapiv2_dot_options_dot_annotations__pb2
from google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*scanoss/api/common/v2/scanoss-common.proto\x12\x15scanoss.api.common.v2\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\"T\n\x0eStatusResponse\x12\x31\n\x06status\x18\x01 \x01(\x0e\x32!.scanoss.api.common.v2.StatusCode\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1e\n\x0b\x45\x63hoRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1f\n\x0c\x45\x63hoResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"k\n\x10\x43omponentRequest\x12\x11\n\x04purl\x18\x01 \x01(\tB\x03\xe0\x41\x02\x12\x13\n\x0brequirement\x18\x02 \x01(\t:/\x92\x41,2*{\"purl\":\"pkg:github/scanoss/engine@1.0.0\"}\"\xc8\x01\n\x11\x43omponentsRequest\x12@\n\ncomponents\x18\x01 \x03(\x0b\x32\'.scanoss.api.common.v2.ComponentRequestB\x03\xe0\x41\x02:q\x92\x41n2l{\"components\":[{\"purl\":\"pkg:github/scanoss/engine@1.0.0\"},{\"purl\":\"pkg:github/scanoss/scanoss.py@v1.30.0\"}]}\"v\n\x0bPurlRequest\x12\x37\n\x05purls\x18\x01 \x03(\x0b\x32(.scanoss.api.common.v2.PurlRequest.Purls\x1a*\n\x05Purls\x12\x0c\n\x04purl\x18\x01 \x01(\t\x12\x13\n\x0brequirement\x18\x02 \x01(\t:\x02\x18\x01\")\n\x04Purl\x12\x0c\n\x04purl\x18\x01 \x01(\t\x12\x13\n\x0brequirement\x18\x02 \x01(\t*`\n\nStatusCode\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x12\x1b\n\x17SUCCEEDED_WITH_WARNINGS\x10\x02\x12\x0b\n\x07WARNING\x10\x03\x12\n\n\x06\x46\x41ILED\x10\x04\x42/Z-github.com/scanoss/papi/api/commonv2;commonv2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'scanoss.api.common.v2.scanoss_common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z-github.com/scanoss/papi/api/commonv2;commonv2'
  _globals['_COMPONENTREQUEST'].fields_by_name['purl']._loaded_options = None
  _globals['_COMPONENTREQUEST'].fields_by_name['purl']._serialized_options = b'\340A\002'
  _globals['_COMPONENTREQUEST']._loaded_options = None
  _globals['_COMPONENTREQUEST']._serialized_options = b'\222A,2*{\"purl\":\"pkg:github/scanoss/engine@1.0.0\"}'
  _globals['_COMPONENTSREQUEST'].fields_by_name['components']._loaded_options = None
  _globals['_COMPONENTSREQUEST'].fields_by_name['components']._serialized_options = b'\340A\002'
  _globals['_COMPONENTSREQUEST']._loaded_options = None
  _globals['_COMPONENTSREQUEST']._serialized_options = b'\222An2l{\"components\":[{\"purl\":\"pkg:github/scanoss/engine@1.0.0\"},{\"purl\":\"pkg:github/scanoss/scanoss.py@v1.30.0\"}]}'
  _globals['_PURLREQUEST']._loaded_options = None
  _globals['_PURLREQUEST']._serialized_options = b'\030\001'
  _globals['_STATUSCODE']._serialized_start=776
  _globals['_STATUSCODE']._serialized_end=872
  _globals['_STATUSRESPONSE']._serialized_start=150
  _globals['_STATUSRESPONSE']._serialized_end=234
  _globals['_ECHOREQUEST']._serialized_start=236
  _globals['_ECHOREQUEST']._serialized_end=266
  _globals['_ECHORESPONSE']._serialized_start=268
  _globals['_ECHORESPONSE']._serialized_end=299
  _globals['_COMPONENTREQUEST']._serialized_start=301
  _globals['_COMPONENTREQUEST']._serialized_end=408
  _globals['_COMPONENTSREQUEST']._serialized_start=411
  _globals['_COMPONENTSREQUEST']._serialized_end=611
  _globals['_PURLREQUEST']._serialized_start=613
  _globals['_PURLREQUEST']._serialized_end=731
  _globals['_PURLREQUEST_PURLS']._serialized_start=685
  _globals['_PURLREQUEST_PURLS']._serialized_end=727
  _globals['_PURL']._serialized_start=733
  _globals['_PURL']._serialized_end=774
# @@protoc_insertion_point(module_scope)
